export interface SeedSite {
  slug: string;
  name: string;
  country: string;
  district?: string;
  province?: string;
  lat: number;
  lng: number;
  industryType: string;
  riskNotes: string;
  hospital: string;
  police: string;
  status: "normal" | "watch" | "incident";
  approximate?: boolean;
}

export interface SeedAccident {
  slug: string;
  year: number;
  date?: string;
  event: string;
  country: string;
  location: string;
  cause?: string;
  deaths?: number;
  injured?: number;
  impact: string;
  lat?: number;
  lng?: number;
  source?: string;
}

// Detailed sites carried over from the original prototype (verified risk narratives).
export const DETAILED_SITES: SeedSite[] = [
  {
    slug: "hetauda-industrial-estate",
    name: "Hetauda Industrial Estate",
    country: "Nepal",
    district: "Makwanpur",
    province: "Bagmati",
    lat: 27.4287,
    lng: 85.0325,
    industryType: "Cement, brewery, textiles, chemicals",
    riskNotes:
      "Nepal's second-largest industrial estate; mixed heavy and chemical industry inside a district headquarters town. A 2023 fire at the Nepal Brewery premises inside the estate showed how quickly stored materials ignite in the open storage areas.",
    hospital: "Hetauda Hospital",
    police: "Area Police Office, Hetauda",
    status: "normal",
  },
  {
    slug: "birgunj-pathlaiya-corridor",
    name: "Birgunj–Pathlaiya Industrial Corridor",
    country: "Nepal",
    district: "Parsa",
    province: "Madhesh",
    lat: 27.0104,
    lng: 84.877,
    industryType: "LPG/gas bottling, FMCG, cross-border logistics",
    riskNotes:
      "Nepal's third-largest industrial corridor, 25km along the India border, dense with LPG bottling plants. Two separate gas-factory fires here (2017 and earlier) each burned for hours and required cross-border firefighting assistance from Raxaul, India.",
    hospital: "Narayani Sub-Regional Hospital, Birgunj",
    police: "Birgunj Metropolitan Police Circle",
    status: "normal",
  },
  {
    slug: "biratnagar-industrial-area",
    name: "Biratnagar Industrial Area",
    country: "Nepal",
    district: "Morang",
    province: "Koshi",
    lat: 26.4525,
    lng: 87.2718,
    industryType: "Jute, food processing, light manufacturing",
    riskNotes:
      "Home to Biratnagar Jute Mills, Nepal's first-ever industry; ageing, partly disused mill buildings caught fire in Feb 2024, with police suspecting arson rather than accidental short-circuit.",
    hospital: "Koshi Hospital, Biratnagar",
    police: "Biratnagar Metropolitan Police Range",
    status: "normal",
  },
  {
    slug: "bhopal-union-carbide-site",
    name: "Bhopal — Union Carbide site (historical)",
    country: "India",
    district: "Bhopal",
    province: "Madhya Pradesh",
    lat: 23.2599,
    lng: 77.4126,
    industryType: "Decommissioned pesticide plant (MIC)",
    riskNotes:
      "Site of the 1984 methyl isocyanate gas leak, the world's worst industrial disaster. Included here as the reference case for chemical-release risk modelling, not an active facility.",
    hospital: "Bhopal Memorial Hospital & Research Centre",
    police: "Hanumanganj Police Station, Bhopal",
    status: "normal",
  },
  {
    slug: "gopalapatnam-chemical-belt",
    name: "Gopalapatnam chemical belt, Visakhapatnam",
    country: "India",
    district: "Visakhapatnam",
    province: "Andhra Pradesh",
    lat: 17.7231,
    lng: 83.2185,
    industryType: "Polymer / petrochemical plants",
    riskNotes:
      "Site of the May 2020 LG Polymers styrene vapour leak (13 dead, 1,000+ sickened), traced to poor tank maintenance and storage during a COVID-lockdown restart.",
    hospital: "King George Hospital, Visakhapatnam",
    police: "Gopalapatnam Police Station",
    status: "normal",
  },
  {
    slug: "ashulia-savar-garment-belt",
    name: "Ashulia–Savar garment belt, Dhaka",
    country: "Bangladesh",
    district: "Dhaka",
    lat: 23.8398,
    lng: 90.265,
    industryType: "Ready-made garment factories",
    riskNotes:
      "Dense export-garment manufacturing zone. Tazreen Fashions fire (Nov 2012, 112 dead) and the Rana Plaza collapse (Apr 2013, 1,136 dead) both occurred in this belt — the two deadliest industrial disasters in Bangladesh's history.",
    hospital: "Enam Medical College Hospital, Savar",
    police: "Ashulia Police Station",
    status: "normal",
  },
  {
    slug: "tongi-gazipur-industrial-zone",
    name: "Tongi–Gazipur industrial zone",
    country: "Bangladesh",
    district: "Gazipur",
    lat: 23.893,
    lng: 90.402,
    industryType: "Packaging, food, light chemical",
    riskNotes:
      "Tampaco Foils packaging factory fire (Sept 2016) killed at least 34 people, one of several boiler/chemical-linked fires in this dense zone north of Dhaka.",
    hospital: "Shaheed Tajuddin Ahmad Medical College Hospital, Gazipur",
    police: "Tongi Police Station",
    status: "normal",
  },
  {
    slug: "site-baldia-town-karachi",
    name: "SITE industrial area, Baldia Town, Karachi",
    country: "Pakistan",
    district: "Karachi",
    lat: 24.926,
    lng: 66.975,
    industryType: "Textile / garment export factories",
    riskNotes:
      "Site of the Sept 2012 Ali Enterprises fire — 259 dead — the deadliest factory fire recorded anywhere. Locked exit doors and barred windows turned a containable fire into a mass-casualty event.",
    hospital: "Abbasi Shaheed Hospital, Karachi",
    police: "Baldia Town Police Station",
    status: "normal",
  },
  {
    slug: "gulshan-i-ravi-lahore",
    name: "Gulshan-i-Ravi industrial area, Lahore",
    country: "Pakistan",
    district: "Lahore",
    lat: 31.53,
    lng: 74.31,
    industryType: "Footwear, leather, light manufacturing",
    riskNotes:
      "A shoe factory fire here on the same day as the Baldia blaze (Sept 2012) killed 25 workers after a generator spark ignited stored chemicals at the compound's only entry/exit point.",
    hospital: "Jinnah Hospital, Lahore",
    police: "Gulshan-i-Ravi Police Station",
    status: "normal",
  },
  {
    slug: "kiriporuwa-estate-yatiyanthota",
    name: "Kiriporuwa Estate, Yatiyanthota",
    country: "Sri Lanka",
    lat: 6.993,
    lng: 80.287,
    industryType: "Latex / rubber processing",
    riskNotes:
      "A rubber-processing machine explosion here (Nov 2025) killed a worker; unions cite recurring absence of machine safety guards across plantation-linked processing factories in this belt.",
    hospital: "Avissawella Base Hospital",
    police: "Yatiyanthota Police Station",
    status: "normal",
  },
  {
    slug: "salawa-ammunition-depot",
    name: "Salawa ammunition depot, Homagama (Colombo)",
    country: "Sri Lanka",
    district: "Colombo",
    lat: 6.845,
    lng: 80.045,
    industryType: "Military ordnance storage",
    riskNotes:
      "A June 2016 chain of explosions at this depot forced thousands to evacuate for a full day — a reminder that hazardous-storage risk near Colombo isn't limited to civilian factories.",
    hospital: "Colombo National Hospital",
    police: "Homagama Police Station",
    status: "normal",
  },
];

// Lightweight entries from the Government of Nepal industrial-area register (approximate
// district-center coordinates; hospital/police and detailed risk narrative pending admin
// verification — flagged via `approximate: true`).
export const NEPAL_REGISTER_SITES: SeedSite[] = [
  {
    slug: "balaju-industrial-district",
    name: "Balaju Industrial District",
    country: "Nepal",
    district: "Kathmandu",
    province: "Bagmati",
    lat: 27.73,
    lng: 85.3,
    industryType: "Nepal's first industrial area (1960); medium-scale mixed manufacturing",
    riskNotes: "Coordinates approximate (district center) — add verified risk assessment via admin panel.",
    hospital: "Bir Hospital",
    police: "Area Police Office, Balaju",
    status: "normal",
    approximate: true,
  },
  {
    slug: "patan-industrial-estate",
    name: "Patan Industrial Estate",
    country: "Nepal",
    district: "Lalitpur",
    province: "Bagmati",
    lat: 27.665,
    lng: 85.324,
    industryType: "Cottage industries, handicrafts",
    riskNotes: "Coordinates approximate (district center) — add verified risk assessment via admin panel.",
    hospital: "Patan Hospital",
    police: "District Police Office, Lalitpur",
    status: "normal",
    approximate: true,
  },
  {
    slug: "bhaktapur-industrial-estate",
    name: "Bhaktapur Industrial Estate",
    country: "Nepal",
    district: "Bhaktapur",
    province: "Bagmati",
    lat: 27.671,
    lng: 85.4298,
    industryType: "Cottage industries",
    riskNotes: "Coordinates approximate (district center) — add verified risk assessment via admin panel.",
    hospital: "Bhaktapur Hospital",
    police: "District Police Office, Bhaktapur",
    status: "normal",
    approximate: true,
  },
  {
    slug: "mayurdhap-industrial-area",
    name: "Mayurdhap Industrial Area",
    country: "Nepal",
    district: "Makwanpur",
    province: "Bagmati",
    lat: 27.45,
    lng: 85.05,
    industryType: "New industrial zone (under development)",
    riskNotes: "Coordinates approximate (district center) — add verified risk assessment via admin panel.",
    hospital: "Hetauda Hospital",
    police: "District Police Office, Makwanpur",
    status: "normal",
    approximate: true,
  },
  {
    slug: "shaktikhor-industrial-area",
    name: "Shaktikhor Industrial Area",
    country: "Nepal",
    district: "Chitwan",
    province: "Bagmati",
    lat: 27.63,
    lng: 84.58,
    industryType: "New industrial zone, ~401 hectares",
    riskNotes: "Coordinates approximate (district center) — add verified risk assessment via admin panel.",
    hospital: "Bharatpur Hospital",
    police: "District Police Office, Chitwan",
    status: "normal",
    approximate: true,
  },
  {
    slug: "dharan-industrial-estate",
    name: "Dharan Industrial Estate",
    country: "Nepal",
    district: "Sunsari",
    province: "Koshi",
    lat: 26.8065,
    lng: 87.2846,
    industryType: "Small/medium scale manufacturing",
    riskNotes: "Coordinates approximate (district center) — add verified risk assessment via admin panel.",
    hospital: "B.P. Koirala Institute of Health Sciences (BPKIHS) Teaching Hospital, Dharan",
    police: "Area Police Office, Dharan",
    status: "normal",
    approximate: true,
  },
  {
    slug: "itahari-brick-kilns",
    name: "Itahari Brick Kilns",
    country: "Nepal",
    district: "Sunsari",
    province: "Koshi",
    lat: 26.665,
    lng: 87.2718,
    industryType: "Brick manufacturing",
    riskNotes:
      "Site of the 2015-12-14 New Jaya Nepal brick kiln chimney collapse (6 dead, 60 injured) — see Historical Accidents. Coordinates approximate (district center).",
    hospital: "Itahari Hospital",
    police: "Area Police Office, Itahari",
    status: "normal",
    approximate: true,
  },
  {
    slug: "dhankuta-industrial-area",
    name: "Dhankuta Industrial Area",
    country: "Nepal",
    district: "Dhankuta",
    province: "Koshi",
    lat: 26.985,
    lng: 87.335,
    industryType: "Declared but not yet operational",
    riskNotes: "Coordinates approximate (district center) — add verified risk assessment via admin panel.",
    hospital: "Dhankuta District Hospital",
    police: "District Police Office, Dhankuta",
    status: "normal",
    approximate: true,
  },
  {
    slug: "china-nepal-industrial-park",
    name: "China-Nepal Industrial Park",
    country: "Nepal",
    district: "Jhapa (Damak)",
    province: "Koshi",
    lat: 26.6667,
    lng: 87.7,
    industryType: "Largest new industrial zone, China-Nepal cooperation",
    riskNotes: "Coordinates approximate (district center) — add verified risk assessment via admin panel.",
    hospital: "AMDA Hospital, Damak",
    police: "Area Police Office, Damak",
    status: "normal",
    approximate: true,
  },
  {
    slug: "butwal-industrial-estate",
    name: "Butwal Industrial Estate",
    country: "Nepal",
    district: "Rupandehi",
    province: "Lumbini",
    lat: 27.7,
    lng: 83.4486,
    industryType: "Small/medium scale manufacturing",
    riskNotes: "Coordinates approximate (district center) — add verified risk assessment via admin panel.",
    hospital: "Lumbini Provincial Hospital, Butwal",
    police: "Area Police Office, Butwal",
    status: "normal",
    approximate: true,
  },
  {
    slug: "bhairahawa-industrial-area",
    name: "Bhairahawa Industrial Area",
    country: "Nepal",
    district: "Rupandehi",
    province: "Lumbini",
    lat: 27.5041,
    lng: 83.4519,
    industryType: "Sugar factories",
    riskNotes: "Coordinates approximate (district center) — add verified risk assessment via admin panel.",
    hospital: "Lumbini Provincial Hospital, Butwal",
    police: "District Police Office, Rupandehi",
    status: "normal",
    approximate: true,
  },
  {
    slug: "motipur-industrial-area",
    name: "Motipur Industrial Area",
    country: "Nepal",
    district: "Rupandehi",
    province: "Lumbini",
    lat: 27.62,
    lng: 83.47,
    industryType: "New industrial zone, ~935 bighas",
    riskNotes: "Coordinates approximate (district center) — add verified risk assessment via admin panel.",
    hospital: "Lumbini Provincial Hospital, Butwal",
    police: "District Police Office, Rupandehi",
    status: "normal",
    approximate: true,
  },
  {
    slug: "nepalgunj-industrial-estate",
    name: "Nepalgunj Industrial Estate",
    country: "Nepal",
    district: "Banke",
    province: "Lumbini",
    lat: 28.05,
    lng: 81.6167,
    industryType: "Small/medium scale manufacturing",
    riskNotes: "Coordinates approximate (district center) — add verified risk assessment via admin panel.",
    hospital: "Bheri Hospital, Nepalgunj",
    police: "District Police Office, Banke",
    status: "normal",
    approximate: true,
  },
  // Three government-run industrial estates (IDML) missing from the original register.
  {
    slug: "pokhara-industrial-estate",
    name: "Pokhara Industrial Estate",
    country: "Nepal",
    district: "Kaski",
    province: "Gandaki",
    lat: 28.2096,
    lng: 83.9856,
    industryType: "Small/medium scale manufacturing",
    riskNotes: "One of Nepal's 10 IDML-managed industrial districts. Coordinates approximate (district center) — add verified risk assessment via admin panel.",
    hospital: "Western Regional Hospital (Gandaki Hospital), Pokhara",
    police: "District Police Office, Kaski",
    status: "normal",
    approximate: true,
  },
  {
    slug: "birendranagar-industrial-estate",
    name: "Birendranagar Industrial Estate",
    country: "Nepal",
    district: "Surkhet",
    province: "Karnali",
    lat: 28.6039,
    lng: 81.6317,
    industryType: "Small/medium scale manufacturing",
    riskNotes: "One of Nepal's 10 IDML-managed industrial districts. Coordinates approximate (district center) — add verified risk assessment via admin panel.",
    hospital: "Provincial Hospital, Birendranagar (Karnali Province)",
    police: "District Police Office, Surkhet",
    status: "normal",
    approximate: true,
  },
  {
    slug: "gajendra-narayan-singh-industrial-estate",
    name: "Gajendra Narayan Singh Industrial Estate",
    country: "Nepal",
    district: "Saptari",
    province: "Koshi",
    lat: 26.5387,
    lng: 86.7461,
    industryType: "Small/medium scale manufacturing",
    riskNotes: "Located in Rajbiraj; one of Nepal's 10 IDML-managed industrial districts. Coordinates approximate (district center) — add verified risk assessment via admin panel.",
    hospital: "Gajendra Narayan Singh Sagarmatha Zonal Hospital, Rajbiraj",
    police: "District Police Office, Saptari",
    status: "normal",
    approximate: true,
  },
  // Brick kilns — Nepal's brick sector runs ~1,349 factories nationwide (Kathmandu Post,
  // Jan 2026), heavily concentrated in Bhaktapur/Lalitpur. These two entries are verified,
  // named/documented clusters — not exhaustive of every kiln.
  {
    slug: "harisiddhi-brick-tiles-factory",
    name: "Harisiddhi Brick and Tiles Factory",
    country: "Nepal",
    district: "Lalitpur",
    province: "Bagmati",
    lat: 27.628,
    lng: 85.333,
    industryType: "Brick and tile manufacturing",
    riskNotes:
      "Nepal's oldest and largest mechanized brick factory (operating since 1970, ~700 workers, ~80 million bricks/year). Brick kilns nationally carry recurring chimney-collapse and brick-pile-collapse risk — see Historical Accidents for past incidents at other kilns.",
    hospital: "Patan Hospital",
    police: "District Police Office, Lalitpur",
    status: "normal",
  },
  {
    slug: "bhaktapur-brick-kiln-cluster",
    name: "Bhaktapur Brick Kiln Cluster",
    country: "Nepal",
    district: "Bhaktapur",
    province: "Bagmati",
    lat: 27.671,
    lng: 85.4298,
    industryType: "Brick manufacturing (dense kiln concentration)",
    riskNotes:
      "Bhaktapur district has the highest brick-kiln concentration in the Kathmandu Valley (~60 of the valley's ~89-110 kilns per recent surveys), driving both air-quality and structural-safety concerns (chimney collapse, brick-pile collapse). Distinct from the general Bhaktapur Industrial Estate entry. Coordinates approximate (district center).",
    hospital: "Bhaktapur Hospital",
    police: "District Police Office, Bhaktapur",
    status: "normal",
    approximate: true,
  },
];

export const ALL_SITES: SeedSite[] = [...DETAILED_SITES, ...NEPAL_REGISTER_SITES];

export const HISTORICAL_ACCIDENTS: SeedAccident[] = [
  {
    slug: "bhopal-gas-leak-1984",
    year: 1984,
    event: "Bhopal gas leak (Union Carbide)",
    country: "India",
    location: "Bhopal, Madhya Pradesh",
    impact: "2,259+ immediate deaths, half a million exposed — world's worst industrial disaster",
    lat: 23.2599,
    lng: 77.4126,
  },
  {
    slug: "ali-enterprises-fire-2012",
    year: 2012,
    event: "Ali Enterprises (Baldia Town) factory fire",
    country: "Pakistan",
    location: "Karachi",
    impact: "259 dead — deadliest recorded factory fire",
    lat: 24.926,
    lng: 66.975,
  },
  {
    slug: "lahore-shoe-factory-fire-2012",
    year: 2012,
    event: "Lahore shoe factory fire",
    country: "Pakistan",
    location: "Gulshan-i-Ravi, Lahore",
    impact: "25 dead, same day as the Baldia fire",
    lat: 31.53,
    lng: 74.31,
  },
  {
    slug: "tazreen-fashions-fire-2012",
    year: 2012,
    event: "Tazreen Fashions factory fire",
    country: "Bangladesh",
    location: "Ashulia, Dhaka",
    impact: "112 dead — deadliest factory fire in Bangladesh's history",
    lat: 23.8398,
    lng: 90.265,
  },
  {
    slug: "rana-plaza-collapse-2013",
    year: 2013,
    event: "Rana Plaza collapse",
    country: "Bangladesh",
    location: "Savar, Dhaka",
    impact: "1,136 dead — worst industrial accident in Bangladesh",
    lat: 23.8151,
    lng: 90.2528,
  },
  {
    slug: "tampaco-foils-fire-2016",
    year: 2016,
    event: "Tampaco Foils packaging factory fire",
    country: "Bangladesh",
    location: "Tongi, Gazipur",
    impact: "34+ dead",
    lat: 23.893,
    lng: 90.402,
  },
  {
    slug: "salawa-depot-explosions-2016",
    year: 2016,
    event: "Salawa ammunition depot explosions",
    country: "Sri Lanka",
    location: "Homagama, Colombo",
    impact: "Thousands evacuated, multiple injured over 24-hour blast sequence",
    lat: 6.845,
    lng: 80.045,
  },
  {
    slug: "birgunj-gas-factory-fire-2017",
    year: 2017,
    event: "Birgunj gas factory fire (Super Gas)",
    country: "Nepal",
    location: "Sugauli Birta, Birgunj",
    impact: "2 dead (incl. firefighter), 6 injured, 9-hour blaze",
    lat: 27.0104,
    lng: 84.877,
  },
  {
    slug: "lg-polymers-leak-2020",
    year: 2020,
    event: "LG Polymers styrene gas leak",
    country: "India",
    location: "Visakhapatnam, Andhra Pradesh",
    impact: "13 dead, 1,000+ sickened",
    lat: 17.7231,
    lng: 83.2185,
  },
  {
    slug: "biratnagar-jute-mills-fire-2024",
    year: 2024,
    event: "Biratnagar Jute Mills fire",
    country: "Nepal",
    location: "Biratnagar",
    impact: "Raw material & machinery loss ~NPR 2 million; suspected arson",
    lat: 26.4525,
    lng: 87.2718,
  },
  {
    slug: "kiriporuwa-explosion-2025",
    year: 2025,
    event: "Kiriporuwa Estate rubber factory explosion",
    country: "Sri Lanka",
    location: "Yatiyanthota",
    impact: "1 dead, 2 injured — cited lack of machine safety guards",
    lat: 6.993,
    lng: 80.287,
  },
  // Nepal-specific accidents from the Government of Nepal accident register.
  {
    slug: "new-jaya-nepal-chimney-collapse-2015",
    year: 2015,
    date: "2015-12-14",
    event: "New Jaya Nepal Brick Kiln Chimney Collapse",
    country: "Nepal",
    location: "Itahari, Sunsari",
    cause: "Chimney structural collapse",
    deaths: 6,
    injured: 60,
    impact: "6 dead, 60 injured — chimney structural collapse",
    lat: 26.665,
    lng: 87.2718,
  },
  {
    slug: "brick-pile-collapse-2017",
    year: 2017,
    date: "2017-12-12",
    event: "Brick Pile Collapse",
    country: "Nepal",
    location: "Kalika Municipality, Chitwan",
    cause: "Collapse of stacked brick pile",
    deaths: 1,
    injured: 8,
    impact: "1 dead, 8 injured — collapse of stacked brick pile",
    lat: 27.65,
    lng: 84.43,
  },
  {
    slug: "steel-factory-fire-2021",
    year: 2021,
    date: "2021-06-20",
    event: "Steel Factory Fire",
    country: "Nepal",
    location: "Nepal (exact plant unspecified)",
    cause: "Fire mishap",
    deaths: 2,
    impact: "2 dead — fire mishap at a steel manufacturing plant",
  },
  {
    slug: "kamalpokhari-gas-cylinder-explosion",
    year: 2015,
    event: "Kamalpokhari Gas Cylinder Explosion",
    country: "Nepal",
    location: "Kamalpokhari, Kathmandu",
    cause: "Cooking gas cylinder explosion",
    deaths: 2,
    injured: 11,
    impact: "2 dead, 11 injured — cooking gas cylinder explosion (exact date not recorded)",
    lat: 27.7172,
    lng: 85.324,
  },
  {
    slug: "krishna-brick-kiln-collapse-2026",
    year: 2026,
    date: "2026-05-15",
    event: "Krishna Brick Kiln Collapse",
    country: "Nepal",
    location: "Haripur Municipality, Sarlahi",
    cause: "Brick stack collapse during unloading",
    deaths: 3,
    injured: 2,
    impact: "3 dead, 2 injured — brick stack collapse during unloading",
    lat: 26.95,
    lng: 85.5667,
  },
  {
    slug: "tulsipur-brick-kiln-wall-collapse-2026",
    year: 2026,
    date: "2026-04-12",
    event: "Tulsipur Brick Kiln Wall Collapse",
    country: "Nepal",
    location: "Tulsipur, Dang",
    cause: "Kiln wall collapse",
    deaths: 1,
    injured: 1,
    impact: "1 dead, 1 injured — kiln wall collapse",
    lat: 28.13,
    lng: 82.2967,
  },
  {
    slug: "jyoti-distillery-boiler-explosion-2025",
    year: 2025,
    date: "2025-12-27",
    event: "Jyoti Distillery Boiler Explosion",
    country: "Nepal",
    location: "Katahariya Municipality, Rautahat",
    cause: "Boiler explosion",
    deaths: 1,
    injured: 6,
    impact: "1 dead, 6 injured — boiler explosion at a distillery",
    lat: 26.9833,
    lng: 85.2833,
  },
];
